### ISSUE TITLE
PATCH saving sends all the model data to the server

### ISSUE THREAD

**Issue by Toddish** [jj-studio/Backbone-JJRelational#12]
When passing the ```{ patch : true }``` option when saving a model, the whole model is sent to the server, not just the data passed in.

```javascript
model.save({ published : 1 }, { patch : true });
```

Will send all the model's attributes to the server, not just *published*.

**Comment by johnnycrab** [comment]
Hey, thanks for the improvement! Sorry for getting back so late, but I'll check this within the next few days, too busy right now...

Thanks again for contributing!

**Comment by sarink** [comment]
Thanks!
