### ISSUE TITLE
Saving is...backwards?

### ISSUE THREAD

**Issue by sarink** [jj-studio/Backbone-JJRelational#15]
In the "saving and fetching" example written in the docs....

a Publisher has_many Authors (implied: each Author belongs_to a Publisher)
an Author has_many Books (implied: each Book belongs_to an Author)

If you save a Publisher, shouldn't the Publisher (without its related models, so Authors in this case) be saved by itself? After this succeeds, then the Authors should save (since they now possess a foreign key to a "real" Publisher), and after the Authors save, only then should the Books save.

Have I just been drawing/building schemas upside-down my whole life?

**Comment by johnnycrab** [comment]
Yes, the whole saving part needs some rethinking.

Consider for example  
Publisher --> has_many --> Authors
Authors --> has_one --> Father

Saving a publisher should save publisher first, then fathers, then authors.
We went the "easy" way and simply said, "okay, when saving a model, recursively save all related models and bubble up to the top; server obviously needs to handle things anyway". This approach is not optimal of course.

**Comment by sarink** [comment]
What about...

if you have a has_many relation, and that relation has a has_one that points to you, then you get saved first, and tell the other model to save only after you have?
